### ISSUE TITLE
Is there a way to use a PS3 guitar controller on PC?

### ISSUE THREAD

**Issue by yuri-lisboa** [ChristopherJMiller/ArduinoGuitarHero#3]

**Comment by ChristopherJMiller** [comment]
While I'm unsure of the specifics of the PS3 guitar controller, there's a good chance under the hood it may just register as a Duelshock 3 Controller with some interesting mappings. If that's the case, you could try something like [Better DS3](https://betterds3.ciebiera.net/) or a similar tool that allows you to use PS3 controllers on PC.

However, closing this issue since this repository is not intended to cover usage for PS3 guitars.
